add opendata.dwd.de to network check

diff --git a/.github/workflows/test_mac.yml b/.github/workflows/test_mac.yml
--- a/.github/workflows/test_mac.yml
+++ b/.github/workflows/test_mac.yml
@@ -27,6 +27,7 @@ jobs:
           echo "My IP address: $(curl -s ipinfo.io/ip)"; true
           { set -o pipefail; curl -s -I http://bbbike.de/robots.txt | head -1; } || { echo "::warning::network check on bbbike.de port 80 failed";            echo "BBBIKE_TEST_SKIP_BBBIKE_DE=1"  >> "$GITHUB_ENV"; }
           { set -o pipefail; curl -s -I https://download.bbbike.org | head -1; } || { echo "::warning::network check on download.bbbike.org port 443 failed"; echo "BBBIKE_TEST_SKIP_BBBIKE_ORG=1" >> "$GITHUB_ENV"; }
+          { set -o pipefail; curl -s -I https://opendata.dwd.de | head -1; } || { echo "::warning::network check on opendata.dwd.de port 443 failed"; }
       - name: Install prerequisites (brew)
         run: |
           set -ex
