github actions: test with perl 5.14.4

diff --git a/.github/workflows/test_perl_versions.yml b/.github/workflows/test_perl_versions.yml
--- a/.github/workflows/test_perl_versions.yml
+++ b/.github/workflows/test_perl_versions.yml
@@ -5,7 +5,31 @@ on:
 
 jobs:
   test_perl_versions:
+    name: Docker tests with ${{ matrix.perl_version }}
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - perl_version:               5.14.4-buster
+            bbbike_test_skip_mapserver: 1
+    env:
+      TRY_MYDEBS_BBBIKE_DE_FALLBACK_PORT: 1
     steps:
-      - name: dummy
-        run: true
+      - name: network check
+        run: |
+          set -ex
+          echo "My IP address: $(curl -s ipinfo.io/ip)"; true
+          { set -o pipefail; curl -s -I http://bbbike.de/robots.txt | head -1; } || { echo "::warning::network check on bbbike.de port 80 failed";            echo "BBBIKE_TEST_SKIP_BBBIKE_DE=1"  >> "$GITHUB_ENV"; }
+          { set -o pipefail; curl -s -I https://download.bbbike.org | head -1; } || { echo "::warning::network check on download.bbbike.org port 443 failed"; echo "BBBIKE_TEST_SKIP_BBBIKE_ORG=1" >> "$GITHUB_ENV"; }
+          { set -o pipefail; curl -s -I http://mydebs.bbbike.de:8000/dists/jessie/InRelease | head -1; true; } || { echo "::warning::network check on port 8000 failed"; }
+      - uses: actions/checkout@v4
+      - name: Build and test
+        run: |
+          set -e
+          sudo apt-get install -y libipc-run-perl
+          ./miscsrc/docker-bbbike test --dist perl --distver ${{ matrix.perl_version }} --src local --jobs 8 \
+            --env BBBIKE_TEST_SKIP_MODPERL=1 --env USE_MODPERL=0 --env USE_SYSTEM_PERL=0 \
+            --env BBBIKE_TEST_SKIP_MAPSERVER=${{ matrix.bbbike_test_skip_mapserver }} \
+            --env BBBIKE_TEST_SKIP_BBBIKE_DE=${BBBIKE_TEST_SKIP_BBBIKE_DE:-0} \
+            --env BBBIKE_TEST_SKIP_BBBIKE_ORG=${BBBIKE_TEST_SKIP_BBBIKE_ORG:-0} \
+            --build-env TRY_MYDEBS_BBBIKE_DE_FALLBACK_PORT=${{ env.TRY_MYDEBS_BBBIKE_DE_FALLBACK_PORT }}
