github actions: try fallback port for mydebs

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -38,8 +38,12 @@ jobs:
 
     steps:
     - name: network check
+      shell: bash
       run: |
-        curl -s -I http://bbbike.de/robots.txt | head -1; true
+        set -ex
+        echo "My IP address: $(curl -s ipinfo.io/ip)"; true
+        { set -o pipefail; curl -s -I http://bbbike.de/robots.txt | head -1; } || { echo "::warning::network check on port 80 failed"; }
+        { set -o pipefail; curl -s -I http://mydebs.bbbike.de:8000/dists/jessie/InRelease | head -1; true; } || { echo "::warning::network check on port 8000 failed"; }
     - name: apt hacks
       # the already installed libgd3 conflicts with libgd-dev to be installed
       # also, /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
@@ -56,6 +60,7 @@ jobs:
         USE_BBBIKE_PPA:           ${{ matrix.use_bbbike_ppa }}
         BBBIKE_TEST_SKIP_MODPERL: ${{ matrix.bbbike_test_skip_modperl }}
         BBBIKE_TEST_GUI:          ${{ matrix.bbbike_test_gui }}
+        TRY_MYDEBS_BBBIKE_DE_FALLBACK_PORT: 1
       run: |
         set -e
         export TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE
@@ -93,38 +98,43 @@ jobs:
     strategy:
       matrix:
         include:
-#          - dist:                       debian
-#            distver:                    jessie
-#            bbbike_test_skip_mapserver: 0
-#            use_bbbike_ppa:             0
-#          - dist:                       debian
-#            distver:                    stretch
-#            bbbike_test_skip_mapserver: 0
-#            use_bbbike_ppa:             0
-#          - dist:                       debian
-#            distver:                    buster
-#            bbbike_test_skip_mapserver: 0
-#            use_bbbike_ppa:             0
-#          - dist:                       debian
-#            distver:                    bullseye
-#            bbbike_test_skip_mapserver: 0
-#            use_bbbike_ppa:             0
-#          - dist:                       ubuntu
-#            distver:                    trusty
-#            bbbike_test_skip_mapserver: 0
-#            use_bbbike_ppa:             0
+          - dist:                       debian
+            distver:                    jessie
+            bbbike_test_skip_mapserver: 0
+            use_bbbike_ppa:             0
+          - dist:                       debian
+            distver:                    stretch
+            bbbike_test_skip_mapserver: 0
+            use_bbbike_ppa:             0
+          - dist:                       debian
+            distver:                    buster
+            bbbike_test_skip_mapserver: 0
+            use_bbbike_ppa:             0
+          - dist:                       debian
+            distver:                    bullseye
+            bbbike_test_skip_mapserver: 0
+            use_bbbike_ppa:             0
+          - dist:                       ubuntu
+            distver:                    trusty
+            bbbike_test_skip_mapserver: 0
+            use_bbbike_ppa:             0
           - dist:                       ubuntu
             distver:                    jammy
             bbbike_test_skip_mapserver: 0
             use_bbbike_ppa:             1
+    env:
+      TRY_MYDEBS_BBBIKE_DE_FALLBACK_PORT: 1
     steps:
     - name: network check
+      shell: bash
       run: |
+        set -ex
         echo "My IP address: $(curl -s ipinfo.io/ip)"; true
-        curl -s -I http://bbbike.de/robots.txt | head -1; true
+        { set -o pipefail; curl -s -I http://bbbike.de/robots.txt | head -1; } || { echo "::warning::network check on port 80 failed"; }
+        { set -o pipefail; curl -s -I http://mydebs.bbbike.de:8000/dists/jessie/InRelease | head -1; true; } || { echo "::warning::network check on port 8000 failed"; }
     - uses: actions/checkout@v2
     - name: Build and test
       run: |
         set -e
         sudo apt-get install -y libipc-run-perl
-        ./miscsrc/docker-bbbike test --dist ${{ matrix.dist }} --distver ${{ matrix.distver }} --src local --jobs 8 --env BBBIKE_TEST_SKIP_MAPSERVER=${{ matrix.bbbike_test_skip_mapserver }} --env USE_BBBIKE_PPA=${{ matrix.use_bbbike_ppa }}
+        ./miscsrc/docker-bbbike test --dist ${{ matrix.dist }} --distver ${{ matrix.distver }} --src local --jobs 8 --env BBBIKE_TEST_SKIP_MAPSERVER=${{ matrix.bbbike_test_skip_mapserver }} --env USE_BBBIKE_PPA=${{ matrix.use_bbbike_ppa }} --env TRY_MYDEBS_BBBIKE_DE_FALLBACK_PORT=${{ env.TRY_MYDEBS_BBBIKE_DE_FALLBACK_PORT }}
